/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'intro',
    // {
    //   type: 'category',
    //   label: 'Markdown',
    //   items: [
    //     'Markdown/markdown-syntax'
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Dart',
    //   items: [
    //     'Dart/syntax-basics',
    //     'Dart/constructors',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Flutter',
    //   items: [
    //     'Flutter/introduction'
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Android',
    //   items: [
    //     'Android/introduction'
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Design Patterns',
    //   items: [
    //     'Design Patterns/intro',
    //     'Design Patterns/singleton',
    //     'Design Patterns/adapter',
    //     'Design Patterns/template-method',
    //     'Design Patterns/composite/composite',
    //     'Design Patterns/strategy',
    //     'Design Patterns/state',
    //     'Design Patterns/facade',
    //     'Design Patterns/interpreter',
    //     'Design Patterns/iterator',
    //     'Design Patterns/factory-method',
    //     'Design Patterns/abstract-factory',
    //     'Design Patterns/command',
    //     'Design Patterns/memento',
    //     'Design Patterns/prototype',
    //     'Design Patterns/proxy',
    //     'Design Patterns/decorator',
    //     'Design Patterns/bridge',
    //     'Design Patterns/builder',
    //     'Design Patterns/flyweight',
    //     'Design Patterns/chain-of-responsibility',
    //     'Design Patterns/visitor',
    //     'Design Patterns/mediator',
    //     'Design Patterns/observer',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
};

export default sidebars;
